import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Search from '../components/Search/index';
import { useEffect, useRef, useState } from 'react';
import axios from 'axios';
import Link from 'next/link';

export default function Home() {
  // const searchRef = useRef();
  const [searchQuery, setSearchQuery] = useState('');
  const [searchResults, setSearchResults] = useState([]);

  // Function to get query from search component as prop
  const getQuery = (query) => {
    // console.log(query);
    setSearchQuery(query);
    // console.log(searchQuery);
  };

  // Function to call Search API
  const getResults = async () => {
    try {
      const res = await axios.get('api/search/', {
        params: { q: searchQuery },
      });
      const { data } = res;
      // console.log(data.items);
      setSearchResults(data.items);
      console.log(searchResults);
    } catch (error) {
      console.error(error);
    }
  };

  // Call function to call Search API on updating searchQuery state
  useEffect(() => {
    getResults();
  }, [searchQuery]);

  return (
    <div className={styles.container}>
      <Head>
        <title>YouTube Search App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <Search getQuery={getQuery} />

        {searchQuery ? <h1>Search results for "{searchQuery}"</h1> : ''}
        {searchResults && (
          <div className={styles.grid}>
            {searchResults.map((item, index) => {
              return (
                <div key={index} className={styles.card}>
                  <img
                    src={item.snippet.thumbnails.medium.url}
                    width={item.snippet.thumbnails.medium.width}
                    height={item.snippet.thumbnails.medium.height}
                  />

                  <div className={styles.info}>
                    <Link href={`/${item.id.videoId}`}>
                      <a>
                        <h2>{item.snippet.title}</h2>
                      </a>
                    </Link>
                    <small>{item.snippet.description}</small>
                    <p>
                      <a
                        href={`https://www.youtube.com/channel/${item.snippet.channelId}`}
                        target='_blank'
                        rel='noreferrer'
                      >
                        {item.snippet.channelTitle}
                      </a>
                    </p>
                  </div>
                </div>
              );
            })}
          </div>
        )}
      </main>

      {/* <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  );
}
